# ~/.config/starship.toml

format = """\
    $conda\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $python\
    $rust\
    $env_var\
    $custom\
    $time\
    $line_break\
    $jobs\
    $battery\
    $status\
    $character\
    """

[conda]
symbol = ""
format = "[$symbol$environment]($style) "
ignore_base = false

[time]
disabled = false
use_12hr = true
