[theme]
theme = "solarized-dark"
[icons]
icons = "awesome4"

[[block]]
block = "weather"
autolocate = true
autolocate_interval = 3600
[block.service]
name = "metno"
lang = "en"

[[block]]
block = "custom"
command = "timeout --kill-after 10s 5s /home/hikes/.cargo/bin/dtx"
interval = 30
hide_when_empty = true

[[block]]
block = "battery"
interval = 10
format = "$icon $percentage $time"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp82s0"
format = "$icon $ssid $signal_strength $ip|$ipv6"
interval = 5

[[block]]
block = "time"
interval = 15
timezone = "America/Los_Angeles"
format = "$timestamp.datetime(f:'%I:%M %p') PT"

[[block]]
block = "time"
interval = 15
timezone = "America/New_York"
#format = "%I:%M %p"
format = "$timestamp.datetime(f:'%a %Y-%m-%d %I:%M %p')"
